modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="ancientsmod"
version="1.0.0"
displayName="Ancients Mod"
description='''
Unlock the Ancient City's hidden portal with a special Ancient Igniter.
Journey into the Ancients Dimension — a dark fusion of the Overworld, Nether, End, and Ancient City.
Face Wardens in their villages, battle Soul Phantoms, and survive the Void Creepers.
'''

[[dependencies.ancientsmod]]
modId="forge"
mandatory=true
versionRange="[47.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.ancientsmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
